services:
  # kartowkamarkowkahub.web:
  #   image: ${DOCKER_REGISTRY-}kartowkamarkowkahubweb
  #   build:
  #     context: .
  #     dockerfile: KartowkaMarkowkaHub.Web/Dockerfile
  #   ports:
  #     - 8080:8080
  #     - 8081:8081
  #   depends_on:
  #     - postgreSql

  postgreSql:
    image: postgres:16
    container_name: postgreSql
    restart: always
    volumes:
     - ./docker/postgreSql/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: adminHub
      POSTGRES_PASSWORD: passwordHub
      POSTGRES_DB: HubDb
    ports:
     - 5432:5432

  cacheRedis:
    image: redis:7.4.0-alpine
    container_name: chcheRedis
    restart: always
    ports:
     - 6379:6379
     - 8001:8001 
    
  rabbitmq:
    image: "rabbitmq:4.0.2-management-alpine"
    container_name: "rabbitmq"
    restart: always
    ports: 
      - 5672:5672
      - 15672:15672
      
  #adminer:
  #  image: adminer:4.8.1
  #  container_name: adminer
  #  restart: always
  #  environment: 
  #    ADMINER_DEFAULT_SERVER: postgreSql
  #    ADMINER_DEFAULT_USERNAME: adminHub
  #    ADMINER_DEFAULT_PASSWORD: passwordHub
  #  ports:
  #   - 5000:8080
  #  depends_on:
  #   - postgreSql

  #pgadmin: 
  #    image: dpage/pgadmin4:8
  #    container_name: pgadmin4
  #    restart: always
  #    environment:
  #        "PGADMIN_DEFAULT_EMAIL": test@gmail.com
  #        "PGADMIN_DEFAULT_PASSWORD": pg-admin_1
  #    ports:
  #        - "8086:80"

  #Graylog Stack
  mongodb:
    image: mongo:5.0
    container_name: graylog-mongodb
    networks:
      - graylog-network
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    container_name: graylog-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - graylog-network
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    restart: unless-stopped

  graylog:
    image: graylog/graylog:5.1
    container_name: graylog
    environment:
      - GRAYLOG_PASSWORD_SECRET=admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8C6976E5B5410415BDE908BD4DEE15DF #admin
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      - "9000:9000"   # Graylog Web UI
      - "12201:12201/udp" # GELF UDP Input
    networks:
      - graylog-network
    restart: unless-stopped

networks:
  graylog-network:
    driver: bridge