version: '3.4'

services:
  kartowkamarkowkahub.web:
    image: ${DOCKER_REGISTRY-}kartowkamarkowkahubweb
    build:
      context: .
      dockerfile: KartowkaMarkowkaHub.Web/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081

  postgreSql:
    image: postgres
    volumes:
     - ./docker/postgreSql/:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: postgreSql
    ports:
     - 5432:5432

  adminer:
    image: adminer
    ports:
     - 5000:8080
    depends_on:
      - postgreSql