version: '3.4'

services:
  kartowkamarkowkahub.web:
    image: ${DOCKER_REGISTRY-}kartowkamarkowkahubweb
    build:
      context: .
      dockerfile: KartowkaMarkowkaHub.Web/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081

  postgreSql:
    image: postgres:16
    container_name: postgreSql
    restart: always
    volumes:
     - ./docker/postgreSql/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: adminHub
      POSTGRES_PASSWORD: passwordHub
      POSTGRES_DB: HubDb
    ports:
     - 5432:5432

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: always
    environment: 
      ADMINER_DEFAULT_SERVER: postgreSql
      ADMINER_DEFAULT_USERNAME: adminHub
      ADMINER_DEFAULT_PASSWORD: passwordHub
    ports:
     - 5000:8080
    depends_on:
     - postgreSql

  pgadmin: 
      image: dpage/pgadmin4:8
      container_name: pgadmin4
      restart: always
      environment:
          "PGADMIN_DEFAULT_EMAIL": test@gmail.com
          "PGADMIN_DEFAULT_PASSWORD": pg-admin_1
      ports:
          - "8086:80"